Update xy-c1-new.yml

diff --git a/.github/workflows/xy-c1-new.yml b/.github/workflows/xy-c1-new.yml
--- a/.github/workflows/xy-c1-new.yml
+++ b/.github/workflows/xy-c1-new.yml
@@ -1,313 +1,77 @@
-name: Build xy-c1 Padavan
+#修改TNAME: K2P-5.0 中的K2P-5.0为你需要编译的型号，注意名称要与configs/templates/目录下的名字相同
+name: H.PSG1218TESTa
 
 on:
   workflow_dispatch:
     inputs:
-      target:
-        type: choice
-        description: 'target to compile'
-        options:
-        - Gee_B70
-        - Nokia-Sbell_A-040W-Q
-        - Xiaomi_CR6606
-        - Xiaomi_CR6608
-        - Xiaomi_CR6609
-        - DLINK_DIR-878
-        - DLINK_DIR-882
-        - JCG_836PRO
-        - JCG_AC860M
-        - JCQ_Q20
-        - JCQ_Q10Pro
-        - JCG_Y2
-        - Phicomm_K2P-USB
-        - Phicomm_K2P
-        - Xiaomi_4
-        - Xiaomi_R3G
-        - Xiaomi_R3P-PB
-        - Xiaomi_R3P
-        - Motorola_MR2600
-        - Raisecom_MSG1500_X.00
-        - Diting_NEWIFI3
-        - Xiaomi_AC2100
-        - Redmi_AC2100
-        - Asus_RT-AC85P
-        - Youhua_WR1200JS
-        - Youhua_WR330
-        - Xiaoyu_C1
-        - Xiaoyu_C3
-        - Xiaoyu_C5
-        - ZTE_E8820S
-        default: Xiaoyu_C1
-      plugins:
-        description: 'json format string of include configs'
+      name:
+        description: "Build Padavan"
         required: true
-        default: '{"vpnsvr":"n","vpncli":"n","vpncmd":"n","ss":"n","v2ray":"n","xray":"n","trojan":"n","singbox":"n","naiveproxy":"n","ssobfs":"n","dnsforwarder":"n","adbyby":"n","adguardhome":"n","smartdns":"n","aliddns":"n","zerotier":"n","ddnsto":"n","wireguard":"n","frpc":"y","aldrive":"n","sqm":"y","mentohust":"n","scutclient":"n","njitclient":"n","minieap":"n","dogcom":"n","transmission":"n","aria":"n","ariaweb":"n"}'
-      firmwarever:
-        description: 'firmware''s version'
-        required: true
-        default: '20240209'
-env:
-  REPOSITORY_URL: https://github.com/keben12345/Padavan-KVR.git
-  WORK_PATH: /opt/padavan-4.4
-  TIME_ZONE: Asia/Shanghai
-  FIRMWARE_DATEPREFIX: $(date +"%Y%m%d")
-  FIRMWARE_AUTHOR: keben
-  FIRMWARE_PATH: /opt/firmwares
+        default: "build"
+  #release:
+  # types: [created]
+  push:
+    tags:
+      - "v*"
+  #  branches:
+  #    - master
+  #  schedule:
+  #    - cron: 0 8 * * 5
+  #watch:
+  #  types: [started]
+
 jobs:
   build:
     runs-on: ubuntu-22.04
     if: github.event.repository.owner.id == github.event.sender.id
 
     steps:
-    - uses: actions/checkout@v4
-    - uses: hendrikmuhs/ccache-action@v1.2.18
-    - uses: Bonnie2980/variable-mapper@master
-      id: export
-      with:
-        key: "${{ github.event.inputs.target }}"
-        map: |
-          {
-            "Gee_B70": {
-              "model": "B70"
-            },
-            "Nokia-Sbell_A-040W-Q": {
-              "model": "BELL-A040WQ"
-            },
-            "Xiaomi_CR6606": {
-              "model": "CR660x"
-            },
-            "Xiaomi_CR6608": {
-              "model": "CR660x"
-            },
-            "Xiaomi_CR6609": {
-              "model": "CR660x"
-            },
-            "DLINK_DIR-878": {
-              "model": "DIR-878"
-            },
-            "DLINK_DIR-882": {
-              "model": "DIR-882"
-            },
-            "JCG_836PRO": {
-              "model": "JCG-836PRO"
-            },
-            "JCG_AC860M": {
-              "model": "JCG-AC860M"
-            },
-            "JCQ_Q20": {
-              "model": "JCG-Q20"
-            },
-            "JCQ_Q10Pro": {
-              "model": "JCG-Q20"
-            },
-            "JCG_Y2": {
-              "model": "JCG-Y2"
-            },
-            "Phicomm_K2P-USB": {
-              "model": "K2P-USB"
-            },
-            "Phicomm_K2P": {
-              "model": "K2P"
-            },
-            "Xiaomi_4": {
-              "model": "MI-4"
-            },
-            "Xiaomi_R3G": {
-              "model": "MI-R3G"
-            },
-            "Xiaomi_R3P-PB": {
-              "model": "MI-R3P-PB"
-            },
-            "Xiaomi_R3P": {
-              "model": "MI-R3P"
-            },
-            "Motorola_MR2600": {
-              "model": "MR2600"
-            },
-            "Raisecom_MSG1500_X.00": {
-              "model": "MSG1500"
-            },
-            "Diting_NEWIFI3": {
-              "model": "NEWIFI3"
-            },
-            "Xiaomi_AC2100": {
-              "model": "R2100"
-            },
-            "Redmi_AC2100": {
-              "model": "RM2100"
-            },
-            "Asus_RT-AC85P": {
-              "model": "RT-AC85P"
-            },
-            "Youhua_WR1200JS": {
-              "model": "WR1200JS"
-            },
-            "Youhua_WR330": {
-              "model": "WR1200JS"
-            },
-            "Xiaoyu_C1": {
-              "model": "XY-C1"
-            },
-            "Xiaoyu_C3": {
-              "model": "XY-C1"
-            },
-            "Xiaoyu_C5": {
-              "model": "XY-C1"
-            },
-            "ZTE_E8820S": {
-              "model": "ZTE-E8820S"
-            },
-            ".*": {
-              "model": "K2P"
-            }
-          }
-        export_to: env
-        mode: first_match
-    - uses: actions/setup-go@v5
-      with:
-        go-version: '1.24.x'
-        check-latest: true
-        cache: false
-    - uses: actions/setup-node@v4
-      with:
-        node-version: 18
-        check-latest: true
-    - name: Initialization environment
-      env:
-        DEBIAN_FRONTEND: noninteractive
-      run: |
-        sudo apt-get update
-        sudo apt install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd \
-        fakeroot kmod cpio git python3-docutils gettext automake autopoint \
-        texinfo build-essential help2man pkg-config zlib1g-dev libgmp3-dev \
-        libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget libc-dev-bin libev-dev
-        sudo timedatectl set-timezone "$TIME_ZONE"
-    - name: Clone source code
-      run: |
-        git clone --depth=1 $REPOSITORY_URL $WORK_PATH
-        cd $WORK_PATH
-        sed -i '/cp -f/d' Makefile
-    - name: Parse json string of include plugins
-      run: |
-        echo "vpnsvr=${{fromJson(github.event.inputs.plugins).vpnsvr}}" >> $GITHUB_ENV
-        echo "vpncli=${{fromJson(github.event.inputs.plugins).vpncli}}" >> $GITHUB_ENV
-        echo "vpncmd=${{fromJson(github.event.inputs.plugins).vpncmd}}" >> $GITHUB_ENV
-        echo "ss=${{fromJson(github.event.inputs.plugins).ss}}" >> $GITHUB_ENV
-        echo "v2ray=${{fromJson(github.event.inputs.plugins).v2ray}}" >> $GITHUB_ENV
-        echo "xray=${{fromJson(github.event.inputs.plugins).xray}}" >> $GITHUB_ENV
-        echo "trojan=${{fromJson(github.event.inputs.plugins).trojan}}" >> $GITHUB_ENV
-        echo "singbox=${{fromJson(github.event.inputs.plugins).singbox}}" >> $GITHUB_ENV
-        echo "naiveproxy=${{fromJson(github.event.inputs.plugins).naiveproxy}}" >> $GITHUB_ENV
-        echo "ssobfs=${{fromJson(github.event.inputs.plugins).ssobfs}}" >> $GITHUB_ENV
-        echo "dnsforwarder=${{fromJson(github.event.inputs.plugins).dnsforwarder}}" >> $GITHUB_ENV
-        echo "adbyby=${{fromJson(github.event.inputs.plugins).adbyby}}" >> $GITHUB_ENV
-        echo "adguardhome=${{fromJson(github.event.inputs.plugins).adguardhome}}" >> $GITHUB_ENV
-        echo "smartdns=${{fromJson(github.event.inputs.plugins).smartdns}}" >> $GITHUB_ENV
-        echo "aliddns=${{fromJson(github.event.inputs.plugins).aliddns}}" >> $GITHUB_ENV
-        echo "zerotier=${{fromJson(github.event.inputs.plugins).zerotier}}" >> $GITHUB_ENV
-        echo "ddnsto=${{fromJson(github.event.inputs.plugins).ddnsto}}" >> $GITHUB_ENV
-        echo "wireguard=${{fromJson(github.event.inputs.plugins).wireguard}}" >> $GITHUB_ENV
-        echo "frpc=${{fromJson(github.event.inputs.plugins).frpc}}" >> $GITHUB_ENV
-        echo "aldrive=${{fromJson(github.event.inputs.plugins).aldrive}}" >> $GITHUB_ENV
-        echo "sqm=${{fromJson(github.event.inputs.plugins).sqm}}" >> $GITHUB_ENV
-        echo "mentohust=${{fromJson(github.event.inputs.plugins).mentohust}}" >> $GITHUB_ENV
-        echo "scutclient=${{fromJson(github.event.inputs.plugins).scutclient}}" >> $GITHUB_ENV
-        echo "njitclient=${{fromJson(github.event.inputs.plugins).njitclient}}" >> $GITHUB_ENV
-        echo "minieap=${{fromJson(github.event.inputs.plugins).minieap}}" >> $GITHUB_ENV
-        echo "dogcom=${{fromJson(github.event.inputs.plugins).dogcom}}" >> $GITHUB_ENV
-        echo "transmission=${{fromJson(github.event.inputs.plugins).transmission}}" >> $GITHUB_ENV
-        echo "aria=${{fromJson(github.event.inputs.plugins).aria}}" >> $GITHUB_ENV
-        echo "ariaweb=${{fromJson(github.event.inputs.plugins).ariaweb}}" >> $GITHUB_ENV
-    - name: Custom config
-      run: |
-        cd $WORK_PATH/trunk
-        if [ ! -f configs/templates/${{ env.model }}.config ] ; then
-        echo "configs/templates/${{ env.model }}.config not found"
-        exit 1
-        fi
-        cp -f configs/templates/${{ env.model }}.config .config
-        ################################################################################################
-        #因不同型号配置功能不一样，所以先把配置项删除，如果你自己要添加其他的，也要写上删除这一条，切记！！！
-        ################################################################################################
-        
-        sed -i 's/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=y/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER=n/g' .config
-        sed -i 's/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=y/CONFIG_FIRMWARE_INCLUDE_MENTOHUST=n/g' .config
-        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=y/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT=n/g' .config
-        sed -i 's/CONFIG_FIRMWARE_INCLUDE_SRELAY=y/CONFIG_FIRMWARE_INCLUDE_SRELAY=n/g' .config
-        sed -i 's/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=y/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT=n/g' .config
-        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
-        
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config 
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_V2RAY/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_XRAY/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_TROJAN/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSOBFS/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_NPC/d' .config
-        sed -i '/CONFIG_FIRMWARE_WEBUI_HIDE_VPN/d' .config
-        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' .config
-        ######################################################################
-        #以下选项是定义你需要的功能（y=集成,n=忽略），重新写入到.config文件
-        ######################################################################
-        ##内网穿透
-        #echo "CONFIG_FIRMWARE_INCLUDE_NPC=y" >> .config 
-        echo "CONFIG_FIRMWARE_INCLUDE_ZEROTIER=y" >> .config #zerotier ~1.3M
-        #echo "CONFIG_FIRMWARE_INCLUDE_FRPC=y" >> .config  #frpc
-        #echo "CONFIG_FIRMWARE_INCLUDE_ALIDDNS=y" >> .config #aliddns
-        ##科学上网##
-        echo "CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS=y" >> .config
-        #echo "CONFIG_FIRMWARE_INCLUDE_V2RAY=y" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_XRAY=y" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_TROJAN=y" >> .config 
-        echo "CONFIG_FIRMWARE_INCLUDE_SSOBFS=y" >> .config 
-        ##vpn
-        echo  "CONFIG_FIRMWARE_WEBUI_HIDE_VPN=n" >> .config
-        echo  "CONFIG_FIRMWARE_INCLUDE_OPENVPN=y" >> .config
-        #echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_SERVER=y" >> .config
-        #echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CLIENT=y" >> .config
-        #echo "CONFIG_FIRMWARE_INCLUDE_SOFTETHERVPN_CMD=y" >> .config
-        
-        ###############################################################################
-        ##########
-        #自定义添加其它功能请参考源码configs/templates/目录下的config文件。按照上面的格式添加即可
-        #格式如下：
-        #sed -i '/自定义项/d' .config
-        #echo "自定义项=y" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION=y" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL=y" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_ARIA=y" >> .config
-        echo "CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL=y" >> .config
-        #sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' .config
-        #echo "CONFIG_FIRMWARE_INCLUDE_TTYD=y" >> .config
-        #########################################################################################
-    - name: Build firmware
-      run: |
-        cd $WORK_PATH
-        sudo make ${{ env.model }} TOOLCHAIN=mipsel-linux-musl
-        echo "FIRMWARE_DATEPREFIX=$(date +"%Y%m%d")" >> $GITHUB_ENV
-    - name: Organize firmware files
-      id: organize
-      run: |
-        mkdir -p $FIRMWARE_PATH/
-        cd $WORK_PATH/trunk/images
-        for firmwarefile in $(ls *.trx)
-        do sudo mv $firmwarefile $FIRMWARE_PATH/${FIRMWARE_DATEPREFIX}"_"${FIRMWARE_AUTHOR}"_"${{ env.model }}"_kernal4.4.trx"
-        done
-        cd $FIRMWARE_PATH
-        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
-        echo "STATUS=success" >> $GITHUB_ENV
-    - name : Upload packages
-      uses: actions/upload-artifact@main
-      if: env.STATUS == 'success'
-      with:
-        name: tsl0922-Padavan44-packages
-        path: ${{ env.FIRMWARE }}
+      - name: Checkout
+        uses: actions/checkout@main
+      - name: Initialization environment
+        env:
+          DEBIAN_FRONTEND: noninteractive
+          token: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          sudo apt-get update
+          sudo apt update
+          sudo apt install libtool-bin gperf python3-docutils autopoint gettext ccache
+      - name: Clone source code
+        run: |
+          git clone -b custom --depth=1 https://github.com/yh793/rt-n56u.git /opt/rt-n56u
+          cd /opt/rt-n56u/toolchain-mipsel
+          sh dl_toolchain.sh
+          mkdir -p /opt/images/
+
+      - name: Get current time
+        uses: 1466587594/get-current-time@v2
+        id: current-time
+        with:
+          format: YYYYMMDDHH
+          utcOffset: "+08:00"
+      - name: Build Firmware
+        env:
+          TNAME: XY-C1 
+        run: |
+          cd /opt/rt-n56u/trunk
+          if [ ! -f configs/templates/$TNAME.config ] ; then
+          echo "configs/templates/$TNAME.config not found "
+          exit 1
+          fi
+          cp -f configs/templates/$TNAME.config .config
+
+          sudo ./clear_tree
+          sudo ./build_firmware_modify $TNAME 0
+          sudo mv -f images/*.trx /opt/images/${TNAME}_Hanwckf_${{ steps.current-time.outputs.formattedTime }}.trx
+          echo "FNAME=$TNAME" >> $GITHUB_ENV
+
+      - name: Organize files
+        id: organize
+        run: |
+          echo "::set-output name=status::success"
+      - name: Upload packages - push to artifact file
+        uses: actions/upload-artifact@main
+        if: steps.organize.outputs.status == 'success'
+        with:
+          name: Padavan-packages
+          path: /opt/images
